<?php

namespace App\Helpers\Constants;

interface PageInterface {

    const PAGE_STATUS_DRAFT = "PAGE_STATUS_DRAFT";
    const PAGE_STATUS_PENDING = "PAGE_STATUS_PENDING";
    const PAGE_STATUS_DELETED = "PAGE_STATUS_DELETED";
    const PAGE_STATUS_PUBLISHED = "PAGE_STATUS_PUBLISHED";
    const PAGE_STATUS_UNPUBLISHED = "PAGE_STATUS_UNPUBLISHED";
}

